Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2021-08, with the labels that each got.

#321 Revert "Bump github.com/onsi/gomega from 1.14.0 to 1.15.0 in /src/database-backup-restore"
  src/database-backup-restore/go.mod
  src/database-backup-restore/go.sum
  src/database-backup-restore/vendor/github.com/onsi/gomega/CHANGELOG.md
  src/database-backup-restore/vendor/github.com/onsi/gomega/env.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/gomega_dsl.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/internal/assertion/assertion.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/internal/defaults/env.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/internal/duration_bundle.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/internal/gomega.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/internal/oraclematcher/oracle_matcher.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/internal/testingtsupport/testing_t_support.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/matchers/and.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/matchers/not.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/matchers/or.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/matchers/with_transform.go
  src/database-backup-restore/vendor/github.com/onsi/gomega/types/types.go
  src/database-backup-restore/vendor/modules.txt
Labels: unscheduled

#322 Revert "Bump github.com/onsi/gomega from 1.14.0 to 1.15.0 in /src/azure-blobstore-backup-restore"
  src/azure-blobstore-backup-restore/go.mod
  src/azure-blobstore-backup-restore/go.sum
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/CHANGELOG.md
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/env.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/gomega_dsl.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/internal/assertion/assertion.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/internal/defaults/env.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/internal/duration_bundle.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/internal/gomega.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/internal/oraclematcher/oracle_matcher.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/internal/testingtsupport/testing_t_support.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/matchers/and.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/matchers/not.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/matchers/or.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/matchers/with_transform.go
  src/azure-blobstore-backup-restore/vendor/github.com/onsi/gomega/types/types.go
  src/azure-blobstore-backup-restore/vendor/golang.org/x/sys/unix/ztypes_linux.go
  src/azure-blobstore-backup-restore/vendor/golang.org/x/sys/windows/types_windows.go
  src/azure-blobstore-backup-restore/vendor/modules.txt
Labels: unscheduled

#323 Bump mariadb from 10.6.3 to 10.6.4
  config/blobs.yml
  packages/database-backup-restorer-mariadb/packaging
  packages/database-backup-restorer-mariadb/spec
Labels: unscheduled, ci

#326 Retry several times trying to workaround flakiness.
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#330 Bump postgres from 10.17 to 10.18
  config/blobs.yml
  packages/database-backup-restorer-postgres-10/packaging
  packages/database-backup-restorer-postgres-10/spec
Labels: ci

#332 Bump postgres from 13.3 to 13.4
  config/blobs.yml
  packages/database-backup-restorer-postgres-13/packaging
  packages/database-backup-restorer-postgres-13/spec
Labels: ci

#337 Update vendored package golang-1-linux
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: unscheduled, bump-golang, ci

#333 Bump postgres from 9.6.22 to 9.6.23
  config/blobs.yml
  packages/database-backup-restorer-postgres-9.6/packaging
  packages/database-backup-restorer-postgres-9.6/spec
Labels: ci

#331 Bump postgres from 11.12 to 11.13
  config/blobs.yml
  packages/database-backup-restorer-postgres-11/packaging
  packages/database-backup-restorer-postgres-11/spec
Labels: ci
