Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2021-11, with the labels that each got.

#443 Update vendored package golang-1-linux
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: bump-golang, ci, ci-inprogress

#455 Bump mariadb from 10.6.4 to 10.6.5
  config/blobs.yml
  packages/database-backup-restorer-mariadb/packaging
  packages/database-backup-restorer-mariadb/spec
  scripts/autobump-mariadb.sh
Labels: ci, ci-inprogress

#456 [ci] Fix pcre bump job
  scripts/autobump-libpcre2.sh
  scripts/autobump-mariadb.sh
Labels: ci-inprogress

#458 [ci] update pcre download URL
  scripts/autobump-libpcre2.sh
Labels: ci-inprogress

#459 Bump libpcre2 from 10.37 to 10.39
  config/blobs.yml
  packages/libpcre2/packaging
  packages/libpcre2/spec
Labels: ci, ci-inprogress

#460 Fix pcre2 BOSH compilation
  packages/libpcre2/packaging
Labels: ci-inprogress

#461 Bump postgres from 10.18 to 10.19
  config/blobs.yml
  packages/database-backup-restorer-postgres-10/packaging
  packages/database-backup-restorer-postgres-10/spec
Labels: ci, ci-inprogress

#471 Revert "Fix pcre2 BOSH compilation"
  packages/libpcre2/packaging
  scripts/autobump-libpcre2.sh
Labels: ci-inprogress

#472 Revert "Bump libpcre2 from 10.37 to 10.39"
  config/blobs.yml
  packages/libpcre2/packaging
  packages/libpcre2/spec
Labels: ci-inprogress

#473 Bump libpcre2 from 10.37 to 10.39
  config/blobs.yml
  packages/libpcre2/packaging
  packages/libpcre2/spec
Labels: ci, ci-inprogress

#462 Bump postgres from 11.13 to 11.14
  config/blobs.yml
  packages/database-backup-restorer-postgres-11/packaging
  packages/database-backup-restorer-postgres-11/spec
Labels: ci, ci-inprogress

#463 Bump postgres from 13.4 to 13.5
  config/blobs.yml
  packages/database-backup-restorer-postgres-13/packaging
  packages/database-backup-restorer-postgres-13/spec
Labels: ci, ci-inprogress

#464 Bump postgres from 9.6.23 to 9.6.24
  config/blobs.yml
  packages/database-backup-restorer-postgres-9.6/packaging
  packages/database-backup-restorer-postgres-9.6/spec
Labels: ci, ci-inprogress

#468 [ci] add script to test package compilation
  scripts/test-package-compilation-for
Labels: ci-inprogress
