Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2021-07, with the labels that each got.

#235 docs: add testing instructions to the README
  Makefile
  README.md
Labels: unscheduled

#236 fix: bump ruby version
  .ruby-version
Labels: unscheduled

#241 #178143824 Autobump MariaDB
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/tasks/bump-mariadb/task.sh
  ci/tasks/bump-mariadb/task.yml
  scripts/bump_mariadb/autobump_to_latest_major.sh
  scripts/bump_mariadb/autobump_to_latest_minor.sh
  scripts/bump_mariadb/autobump_to_latest_patch.sh
  scripts/bump_mariadb/bump_to_specific_version.sh
  scripts/bump_mariadb/current_blob_name.sh
  scripts/bump_mariadb/current_version.sh
  scripts/bump_mariadb/download_specific_version.sh
  scripts/bump_mariadb/list_all_releases.sh
  scripts/bump_mariadb/list_all_stable_releases.sh
  scripts/bump_mariadb/list_new_major_releases.sh
  scripts/bump_mariadb/list_new_minor_releases.sh
  scripts/bump_mariadb/list_new_patch_releases.sh
  scripts/bump_mariadb/list_new_stable_releases.sh
Labels: unscheduled

#242 Update mariadb
  config/blobs.yml
  packages/database-backup-restorer-mariadb/packaging
  packages/database-backup-restorer-mariadb/spec
Labels: ci, unscheduled

#255 #178143824 bump myqsl
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/tasks/bump-mysql/task.sh
  ci/tasks/bump-mysql/task.yml
  scripts/bump_mysql/autobump_to_latest_patch.sh
  scripts/bump_mysql/bump_to_specific_version.sh
  scripts/bump_mysql/current_blobs_name.sh
  scripts/bump_mysql/current_blobs_version.sh
  scripts/bump_mysql/download_specific_version.sh
  scripts/bump_mysql/list_all_releases.sh
  scripts/bump_mysql/list_all_stable_releases.sh
  scripts/bump_mysql/list_new_major_releases.sh
  scripts/bump_mysql/list_new_minor_releases.sh
  scripts/bump_mysql/list_new_patch_releases.sh
  scripts/bump_mysql/list_new_stable_releases.sh
Labels: unscheduled

#257 Update mysql
  config/blobs.yml
  packages/database-backup-restorer-mysql-5.7/packaging
  packages/database-backup-restorer-mysql-5.7/spec
Labels: ci, unscheduled

#261 Add script to autobump postgresql blobs to latest versions
  scripts/autobump-postgresql.sh
  scripts/bump-generic/autobump-all-blobs-at-once.sh
  scripts/bump-generic/autobump-pick-candidate.sh
  scripts/bump-generic/replace-blob-with.sh
Labels: unscheduled

#262 Update vendored package golang-1-linux
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: bump-golang, ci, unscheduled

#263 Update mysql
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: ci, unscheduled

#282 #178143824 bump postgres ci
  ci/tasks/bump-generic/functions.sh
  ci/tasks/bump-generic/task.sh
  ci/tasks/bump-generic/task.yml
  scripts/autobump-postgresql.sh
  scripts/bump-generic/autobump-all-blobs-at-once.sh
  scripts/bump-generic/autobump-pick-candidate.sh
  scripts/bump-generic/replace-blob-with.sh
Labels: unscheduled

#287 Bump postgres from 9.6.14 to 9.6.22
  config/blobs.yml
  packages/database-backup-restorer-postgres-9.6/packaging
  packages/database-backup-restorer-postgres-9.6/spec
Labels: ci, unscheduled

#286 Bump postgres from 9.4.23 to 9.4.26
  config/blobs.yml
  packages/database-backup-restorer-postgres-9.4/packaging
  packages/database-backup-restorer-postgres-9.4/spec
Labels: ci, unscheduled

#284 Bump postgres from 11.4 to 11.12
  config/blobs.yml
  packages/database-backup-restorer-postgres-11/packaging
  packages/database-backup-restorer-postgres-11/spec
Labels: ci, unscheduled

#283 Bump postgres from 10.12 to 10.17
  config/blobs.yml
  packages/database-backup-restorer-postgres-10/packaging
  packages/database-backup-restorer-postgres-10/spec
Labels: ci, unscheduled

#285 Bump postgres from 13.2 to 13.3
  config/blobs.yml
  packages/database-backup-restorer-postgres-13/packaging
  packages/database-backup-restorer-postgres-13/spec
Labels: ci, unscheduled

#290 #178143824 bump boost
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/tasks/bump-generic/functions.sh
  ci/tasks/bump-generic/task.sh
  scripts/autobump-boost.sh
Labels: unscheduled

#291 Bump boost from 1.59.0 to 1.76.0
  config/blobs.yml
  packages/database-backup-restorer-boost/packaging
  packages/database-backup-restorer-boost/spec
Labels: ci, unscheduled

#292 Implement automatic bumping for libpcre2
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  scripts/autobump-libpcre2.sh
Labels: unscheduled

#295 ci: migrate tasks to task repo
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/pipelines/test-github-prs/pipeline.yml
  ci/pipelines/test-github-prs/set-pipeline.sh
  ci/tasks/accept-stories/task.sh
  ci/tasks/accept-stories/task.yml
  ci/tasks/deliver-stories/task.sh
  ci/tasks/deliver-stories/task.yml
  ci/tasks/find-pr-story/task.sh
  ci/tasks/find-pr-story/task.yml
  ci/tasks/merge-pr/task.sh
  ci/tasks/merge-pr/task.yml
  ci/tasks/start-story/task.sh
  ci/tasks/start-story/task.yml
Labels: unscheduled

#296 update merge message
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/pipelines/bbr-sdk-test-infrastructure/pipeline.yml
Labels: unscheduled

#298 Bump mysql from 5.7.33 to 5.7.34
  ci/resources/mysql-releases-resource/assets/test_assets/test_rss.xml
  config/blobs.yml
  packages/database-backup-restorer-mysql-5.7/packaging
  packages/database-backup-restorer-mysql-5.7/spec
Labels: ci, unscheduled

#297 ci: fix create-final-patch job
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#300 fix: really use the libpcre when compiling mariadb
  packages/database-backup-restorer-mariadb/packaging
  packages/database-backup-restorer-mysql-5.6/packaging
  packages/database-backup-restorer-mysql-5.6/spec
  packages/database-backup-restorer-mysql-5.7/packaging
  packages/database-backup-restorer-mysql-5.7/spec
  packages/libpcre2/packaging
Labels: unscheduled
