Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2022-11, with the labels that each got.

#739 Add a script that the autobumper task can use for ncurses
  scripts/autobump-ncurses.sh
  scripts/gnu-keyring.gpg
Labels: unscheduled

#741 chore(dockerize-release): compile BOSH packages concurrently
  .github/dependabot.yml
  ci/dockerfiles/dockerize-release/Dockerfile
  scripts/boshcompiler/Makefile
  scripts/boshcompiler/README.md
  scripts/boshcompiler/go.mod
  scripts/boshcompiler/go.sum
  scripts/boshcompiler/internal/concurrently/concurrently_suite_test.go
  scripts/boshcompiler/internal/concurrently/run.go
  scripts/boshcompiler/internal/concurrently/run_test.go
  scripts/boshcompiler/internal/manifest/manifest.go
  scripts/boshcompiler/internal/manifest/manifest_suite_test.go
  scripts/boshcompiler/internal/manifest/manifest_test.go
  scripts/boshcompiler/internal/workstatus/workstatus.go
  scripts/boshcompiler/main.go
  scripts/boshcompiler/tools/tools.go
Labels: unscheduled

#745 Update vendored package golang-1-linux
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: unscheduled, bump-golang, ci

#760 Condense unit and system workflows in a single Test Pyramid workflow
  .github/workflows/run-test-pyramid.yml
  .github/workflows/system-db-tests.yml
  .github/workflows/unit-tests.yml
  Makefile
  ci/dockerfiles/run-system-db-tests/Dockerfile
  docker-compose.yml
Labels: unscheduled, system-tests

#772 Bump postgres from 10.22 to 10.23
  config/blobs.yml
  packages/database-backup-restorer-postgres-10/packaging
  packages/database-backup-restorer-postgres-10/spec
Labels: unscheduled, ci

#773 Bump postgres from 11.17 to 11.18
  config/blobs.yml
  packages/database-backup-restorer-postgres-11/packaging
  packages/database-backup-restorer-postgres-11/spec
Labels: unscheduled, ci, system-tests, bosh-tests

#774 Bump postgres from 13.8 to 13.9
  config/blobs.yml
  packages/database-backup-restorer-postgres-13/packaging
  packages/database-backup-restorer-postgres-13/spec
Labels: unscheduled, ci, system-tests

#778 Bump mariadb from 10.6.10 to 10.6.11
  config/blobs.yml
  packages/database-backup-restorer-mariadb/packaging
  packages/database-backup-restorer-mariadb/spec
Labels: unscheduled, ci, system-tests

#788 Replace maru-lite with Toolsmiths' cf-d
  ci/manifests/azure-backuper.yml
  ci/manifests/gcs-backuper.yml
  ci/manifests/postgres-11.yml
  ci/manifests/postgres-13.yml
  ci/manifests/postgres-9.4.yml
  ci/manifests/postgres-9.6.yml
  ci/manifests/s3-backuper.yml
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  scripts/autobump-mysql.sh
Labels: unscheduled

#784 Wait for any running workflow to complete before merging the PR
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled, system-tests
