Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2022-09, with the labels that each got.

#702 Feature/mysql 8 support
  ci/manifests/ops-files/dev-release.yml
  config/blobs.yml
  jobs/database-backup-restorer/spec
  jobs/database-backup-restorer/templates/backup
  jobs/database-backup-restorer/templates/restore
  packages/database-backup-restorer-mysql-8.0/packaging
  packages/database-backup-restorer-mysql-8.0/spec
  scripts/autobump-mysql.sh
  src/database-backup-restore/config/utilities.go
  src/database-backup-restore/database/interactor_factory.go
  src/database-backup-restore/database/interactor_factory_test.go
  src/database-backup-restore/integration_tests/database_backup_and_restore_suite_test.go
  src/database-backup-restore/integration_tests/mysql_test.go
  src/database-backup-restore/system_tests/mysql/mysql_tls_test.go
Labels: unscheduled

#703 Make the mysql8 packaging script work in airgapped environments
  packages/database-backup-restorer-mysql-8.0/packaging
Labels: unscheduled

#677 Update vendored package golang-1-linux
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: unscheduled, bump-golang, ci

#711 Bump mariadb from 10.6.9 to 10.6.10
  config/blobs.yml
  packages/database-backup-restorer-mariadb/packaging
  packages/database-backup-restorer-mariadb/spec
Labels: unscheduled, ci

#714 Add a unit tests workflow for sdk-release-tests
  .github/actions/run-golang-unit-tests/Dockerfile
  .github/actions/sdk-template-unit-tests/Dockerfile
  .github/workflows/unit-tests.yml
  Makefile
  README.md
  docker-compose.yml
  scripts/run-template-tests.bash
  src/azure-blobstore-backup-restore/scripts/run-unit-tests.bash
  src/database-backup-restore/scripts/run-unit-tests.bash
  src/gcs-blobstore-backup-restore/scripts/run-unit-tests.bash
  src/s3-blobstore-backup-restore/cmd/s3-blobstore-backup-restore/main_suite_test.go
  src/s3-blobstore-backup-restore/scripts/run-unit-tests.bash
Labels: unscheduled

#704 Add airgap tests
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled
