Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2023-01, with the labels that each got.

#834 Update vendored package golang-1-linux
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: unscheduled, bump-golang, ci

#839 Fix ncurses autobump script
  scripts/autobump-ncurses.sh
Labels: unscheduled

#840 Download gnu-keyring on every execution
  scripts/autobump-ncurses.sh
  scripts/gnu-keyring.gpg
Labels: unscheduled

#846 Fix gpg verify command
  scripts/autobump-ncurses.sh
Labels: unscheduled

#847 Bump ncurses from 6.3 to 6.4
  config/blobs.yml
  packages/database-backup-restorer-mysql-8.0/packaging
  packages/database-backup-restorer-mysql-8.0/spec
Labels: unscheduled, ci
