Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2023-08, with the labels that each got.

#1154 Bump golang-1-linux to version v0.130.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: unscheduled, bump-golang, ci

#1160 Bump cryogenics/essentials to v0.1.61
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1162 Bump golang-1-linux to version v0.131.0
  src/azure-blobstore-backup-restore/go.sum
Labels: unscheduled, bump-golang, ci

#1163 Bump cryogenics/essentials to v0.1.62
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1175 Bump postgres from 11.20 to 11.21
  config/blobs.yml
  packages/database-backup-restorer-postgres-11/packaging
  packages/database-backup-restorer-postgres-11/spec
Labels: unscheduled, ci

#1176 Bump postgres from 13.11 to 13.12
  config/blobs.yml
  packages/database-backup-restorer-postgres-13/packaging
  packages/database-backup-restorer-postgres-13/spec
Labels: unscheduled, ci

#1178 Bump cryogenics/essentials to v0.1.63
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1179 Bump mariadb from 10.6.14 to 10.6.15
  config/blobs.yml
  packages/database-backup-restorer-mariadb/packaging
  packages/database-backup-restorer-mariadb/spec
Labels: unscheduled, ci

#1186 Bump cryogenics/essentials to v0.1.64
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1192 Bump cryogenics/essentials to v0.1.65
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1202 [CI] Add experimental CVE scanner
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1203 Bump cryogenics/essentials to v0.1.66
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1205 Bump cryogenics/essentials to v0.1.67
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1206 fix auto-bumping script
  scripts/autobump-openssl-1.sh
Labels: unscheduled

#1207 fix more issues with the autobumping script
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  scripts/autobump-openssl-1.sh
Labels: unscheduled

#1208 Bump openssl from 1.1.1o to 1.1.1v
  config/blobs.yml
  packages/libopenssl1/packaging
  packages/libopenssl1/spec
  scripts/autobump-openssl-1.sh
Labels: unscheduled, ci

#1209 Bump golang-1-linux to version v0.132.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
  src/azure-blobstore-backup-restore/go.mod
  src/azure-blobstore-backup-restore/go.sum
  src/azure-blobstore-backup-restore/vendor/modules.txt
  src/database-backup-restore/go.mod
  src/database-backup-restore/go.sum
  src/s3-blobstore-backup-restore/go.mod
  src/s3-blobstore-backup-restore/go.sum
  src/system-tests/go.mod
  src/system-tests/go.sum
Labels: unscheduled, bump-golang, ci
