Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2023-05, with the labels that each got.

#1029 Bump mysql from 8.0.32 to 8.0.33
  config/blobs.yml
Labels: unscheduled, ci

#1030 Bump mysql from 5.7.40 to 5.7.42
  ci/resources/mysql-releases-resource/assets/test_assets/test_rss.xml
  config/blobs.yml
  packages/database-backup-restorer-mysql-5.7/packaging
  packages/database-backup-restorer-mysql-5.7/spec
Labels: unscheduled, ci

#1031 Bump golang-1-linux to version v0.125.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
  src/azure-blobstore-backup-restore/go.sum
Labels: unscheduled, bump-golang, ci

#1045 Bump postgres from 11.19 to 11.20
  config/blobs.yml
  packages/database-backup-restorer-postgres-11/packaging
  packages/database-backup-restorer-postgres-11/spec
Labels: unscheduled, ci

#1046 Bump postgres from 13.10 to 13.11
  config/blobs.yml
  packages/database-backup-restorer-postgres-13/packaging
  packages/database-backup-restorer-postgres-13/spec
Labels: unscheduled, ci

#1047 Bump postgres from 15.2 to 15.3
  ci/dockerfiles/run-system-db-tests/postgres/enable_tls.sh
  config/blobs.yml
  packages/database-backup-restorer-postgres-15/packaging
  packages/database-backup-restorer-postgres-15/spec
  src/database-backup-restore/integration_tests/postgres_test.go
Labels: unscheduled, ci

#1048 Bump mariadb from 10.6.12 to 10.6.13
  config/blobs.yml
  packages/database-backup-restorer-mariadb/packaging
  packages/database-backup-restorer-mariadb/spec
Labels: unscheduled, ci

#1052 chore: add bump-ci-task
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.sh
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.sh
  ci/tasks/generate-bosh-deployment-source-file/task.yml
Labels: unscheduled

#1060 feat: remove PostgreSQL 9.4 and 9.6
  config/blobs.yml
  jobs/database-backup-restorer/spec
  jobs/database-backup-restorer/templates/backup
  jobs/database-backup-restorer/templates/restore
  packages/database-backup-restorer-postgres-9.4/packaging
  packages/database-backup-restorer-postgres-9.4/spec
  packages/database-backup-restorer-postgres-9.6/packaging
  packages/database-backup-restorer-postgres-9.6/spec
  src/database-backup-restore/cmd/database-backup-restore/main.go
  src/database-backup-restore/config/utilities.go
  src/database-backup-restore/database/interactor_factory.go
  src/database-backup-restore/database/interactor_factory_test.go
  src/database-backup-restore/integration_tests/database_backup_and_restore_suite_test.go
  src/database-backup-restore/integration_tests/database_backup_restore_test.go
  src/database-backup-restore/integration_tests/postgres_test.go
Labels: unscheduled

#1061 Bump cryogenics/essentials to v0.1.51
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1064 mv essentials img to resources
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1065 Make CI use `bump-golang` for bumping golang
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1068 Bump cryogenics/essentials to v0.1.52
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1070 [ci] remove creds from dev release build
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/tasks/create-dev-release/task.sh
Labels: unscheduled

#1071 Use assumed role in the s3 backup bucket config
  ci/manifests/s3-backuper.yml
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/tasks/sdk-system-blobstore/task.yml
  src/s3-blobstore-backup-restore/cmd/s3-blobstore-backup-restore/main.go
  src/s3-blobstore-backup-restore/cmd/s3-blobstore-backup-restore/main_test.go
  src/s3-blobstore-backup-restore/unversioned/bucket.go
  src/s3-blobstore-backup-restore/unversioned/config.go
  src/s3-blobstore-backup-restore/unversioned/config_test.go
  src/s3-blobstore-backup-restore/versioned/artifact_test.go
  src/s3-blobstore-backup-restore/versioned/bucket.go
  src/s3-blobstore-backup-restore/versioned/config.go
  src/s3-blobstore-backup-restore/versioned/config_test.go
  src/system-tests/s3/s3_helper_test.go
  src/system-tests/s3/s3_unversioned_blobstore_system_test.go
  src/system-tests/s3/s3_versioned_blobstore_system_test.go
  src/system-tests/s3/system_tests_suite_test.go
Labels: unscheduled

#1072 use switch role credentials
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1075 update var name to be inline with other tasks
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1076 Use assumed role credentials for tf
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1077 use "passed" on cryogenics-concourse-tasks
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1078 Update resource credential sources
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled
