Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2023-10, with the labels that each got.

#1260 Use harbor to get cryo-essentials in tasks
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled

#1265 [CI] Allow ci to pick the latest cryo-essentials
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1266 Bump cryogenics/essentials to v0.1.74
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1267 Bump golang-1-linux to version v0.135.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: unscheduled, bump-golang, ci

#1268 Bump golang-1-linux to version v0.136.0
  .final_builds/packages/golang-1-linux/index.yml
Labels: unscheduled, bump-golang, ci

#1271 Bump cryogenics/essentials to v0.1.75
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1272 Use harbor for alias-env task
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1286 Bump golang-1-linux to version v0.138.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: unscheduled, bump-golang, ci

#1287 Add claim retries
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1299 increase timeout for test
  src/s3-blobstore-backup-restore/s3bucket/bucket_helpers_test.go
Labels: unscheduled

#1300 Bump cryogenics/essentials to v0.1.77
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1303 Chore/fix gw user
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1305 Bump cryogenics/essentials to v0.1.78
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1308 Use harbor to get cryo-essential image in the create-final-release task
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1314 source secrets from cerberus
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1315 Update pipeline to test the latest TAS
  ci/pipelines/backup-and-restore-sdk-release/values.yml
Labels: unscheduled

#1317 remove need to create custom firewall rule
  ci/manifests/ops-files/apply_vm_extension.yml
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1318 Bump mysql from 5.7.43 to 5.7.44
  ci/resources/mysql-releases-resource/assets/test_assets/test_rss.xml
  config/blobs.yml
  packages/database-backup-restorer-mysql-5.7/packaging
  packages/database-backup-restorer-mysql-5.7/spec
Labels: unscheduled, ci

#1319 Bump mysql from 8.0.34 to 8.0.35
  config/blobs.yml
Labels: unscheduled, ci

#1325 Use cfd airgapped shepherd
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled
