Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2024-01, with the labels that each got.

#1432 Bump cryogenics/essentials to v0.1.88
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1438 Bump cryogenics/essentials to v0.1.89
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1443 Bump golang-1-linux to version v0.143.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: unscheduled, bump-golang, ci

#1450 Bump cryogenics/essentials to v0.1.90
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/bump-mysql-5.6/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1455 Maintenance/clean out of support db version
  Makefile
  ci/manifests/mysql.yml
  ci/manifests/postgres-10.yml
  ci/manifests/postgres-9.4.yml
  ci/manifests/postgres-9.6.yml
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  ci/resources/mysql-releases-resource/assets/Dockerfile
  ci/resources/mysql-releases-resource/assets/all_test.bash
  ci/resources/mysql-releases-resource/assets/check
  ci/resources/mysql-releases-resource/assets/check.bash
  ci/resources/mysql-releases-resource/assets/check_test.bash
  ci/resources/mysql-releases-resource/assets/in
  ci/resources/mysql-releases-resource/assets/in.bash
  ci/resources/mysql-releases-resource/assets/in_test.bash
  ci/resources/mysql-releases-resource/assets/test_assets/test_input.json
  ci/resources/mysql-releases-resource/assets/test_assets/test_rss.xml
  ci/tasks/bump-mysql-5.6/task.sh
  ci/tasks/bump-mysql-5.6/task.yml
  config/blobs.yml
  docs/database-backup-restore.md
  jobs/database-backup-restorer/spec
  jobs/database-backup-restorer/templates/backup
  jobs/database-backup-restorer/templates/restore
  packages/database-backup-restorer-mysql-5.6/packaging
  packages/database-backup-restorer-mysql-5.6/spec
  packages/database-backup-restorer-mysql-5.7/packaging
  packages/database-backup-restorer-mysql-5.7/spec
  packages/database-backup-restorer-postgres-10/packaging
  packages/database-backup-restorer-postgres-10/spec
  src/database-backup-restore/cmd/database-backup-restore/main.go
  src/database-backup-restore/config/utilities.go
  src/database-backup-restore/database/interactor_factory.go
  src/database-backup-restore/database/interactor_factory_test.go
  src/database-backup-restore/integration_tests/database_backup_and_restore_suite_test.go
  src/database-backup-restore/integration_tests/database_backup_restore_test.go
  src/database-backup-restore/integration_tests/mysql_test.go
  src/database-backup-restore/integration_tests/postgres_test.go
  src/database-backup-restore/system_tests/utils/db.go
Labels: unscheduled

#1469 Increase timeout of the put: mysql-8-0-deployment step to 2hrs
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1475 Bump mysql-server to version 8.0.36
  config/blobs.yml
  packages/database-backup-restorer-mysql-8.0/packaging
Labels: unscheduled, ci, bump-mysql

#1472 Bump cryogenics/essentials to v0.1.91
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1473 Add blob-directory to mysql bump
  .ruby-version
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1484 Bump cryogenics/essentials to v0.1.93
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1485 Use only-variable-name:MYSQL80_VERSION for correct mySql bumping
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1487 drop dependencies on custom ossl and libpcre2
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  config/blobs.yml
  packages/database-backup-restorer-mariadb/packaging
  packages/database-backup-restorer-mariadb/spec
  packages/libopenssl1/packaging
  packages/libopenssl1/spec
  scripts/autobump-openssl-1.sh
Labels: unscheduled

#1488 [ci] read/write git resource linter issues
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1489 Bump cryogenics/essentials to v0.1.94
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1493 Bump cryogenics/essentials to v0.1.95
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1494 Update pipeline to test the latest TAS
  ci/pipelines/backup-and-restore-sdk-release/values.yml
Labels: unscheduled

#1495 Update pipeline to test the latest TAS
  ci/pipelines/backup-and-restore-sdk-release/values.yml
Labels: unscheduled

#1497 Bump cryogenics/essentials to v0.1.96
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies
