Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2024-03, with the labels that each got.

#1557 Bump cryogenics/essentials to v0.1.105
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1569 Bump cryogenics/essentials to v0.1.106
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1573 Bump golang-1-linux to version v0.147.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
  src/azure-blobstore-backup-restore/go.mod
  src/azure-blobstore-backup-restore/vendor/modules.txt
  src/database-backup-restore/go.mod
  src/s3-blobstore-backup-restore/go.mod
  src/system-tests/go.mod
Labels: unscheduled, bump-golang, ci

#1574 Group aws sdk dependabot bumps
  .github/dependabot.yml
  src/s3-blobstore-backup-restore/go.mod
  src/s3-blobstore-backup-restore/go.sum
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/credentials/CHANGELOG.md
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/credentials/go_module_metadata.go
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/internal/checksum/CHANGELOG.md
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/internal/checksum/go_module_metadata.go
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/context.go
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/s3/CHANGELOG.md
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/s3/api_client.go
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/s3/go_module_metadata.go
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_client.go
  src/s3-blobstore-backup-restore/vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  src/s3-blobstore-backup-restore/vendor/modules.txt
Labels: unscheduled

#1581 Bump cryogenics/essentials to v0.1.108
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1607 [ci] Install Ruby version if not present
  ci/tasks/sdk-template-unit-tests/task.yml
Labels: unscheduled

#1606 remove usage of harbor, implement adr-006
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled
