Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2024-06, with the labels that each got.

#1705 [ci] fix mariadb bump
  packages/database-backup-restorer-mariadb/packaging
Labels: unscheduled

#1713 [ci] Fix MariaDB bump
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
  packages/database-backup-restorer-mariadb/packaging
Labels: unscheduled

#1714 Bump golang-1-linux to version v0.152.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
  src/azure-blobstore-backup-restore/go.mod
  src/azure-blobstore-backup-restore/vendor/modules.txt
  src/database-backup-restore/go.mod
  src/s3-blobstore-backup-restore/go.mod
  src/system-tests/go.mod
Labels: unscheduled, bump-golang, ci

#1715 Bump Ruby to 3.3.1
  .ruby-version
  Gemfile.lock
Labels: unscheduled, dependencies

#1716 Bump libpcre2-server to version 10.44
  config/blobs.yml
  packages/libpcre2/packaging
Labels: unscheduled, ci, bump-libpcre2

#1717 [ci] fix autobumpers
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled
