Repository cloudfoundry/backup-and-restore-sdk-release, pull requests merged in 2024-02, with the labels that each got.

#1499 Bump cryogenics/essentials to v0.1.97
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1503 Bump cryogenics/essentials to v0.1.98
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1504 Bump golang-1-linux to version v0.145.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
  src/azure-blobstore-backup-restore/go.mod
  src/azure-blobstore-backup-restore/vendor/modules.txt
  src/database-backup-restore/go.mod
  src/s3-blobstore-backup-restore/go.mod
  src/system-tests/go.mod
Labels: unscheduled, bump-golang, ci

#1505 Bump cryogenics/essentials to v0.1.99
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1506 Bump golang-1-linux to version v0.146.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
  src/azure-blobstore-backup-restore/go.mod
  src/azure-blobstore-backup-restore/vendor/modules.txt
  src/database-backup-restore/go.mod
  src/s3-blobstore-backup-restore/go.mod
  src/system-tests/go.mod
Labels: unscheduled, bump-golang, ci

#1508 Update pipeline to test the latest TAS
  ci/pipelines/backup-and-restore-sdk-release/values.yml
Labels: unscheduled

#1509 Added jobs to manually bump major, minor and patch versions
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1512 Bump cryogenics/essentials to v0.1.102
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1513 Bump postgres from 13.13 to 13.14
  config/blobs.yml
  packages/database-backup-restorer-postgres-13/packaging
Labels: unscheduled, ci

#1514 Bump postgres from 15.5 to 15.6
  ci/dockerfiles/run-system-db-tests/postgres/enable_tls.sh
  config/blobs.yml
  packages/database-backup-restorer-postgres-15/packaging
  src/database-backup-restore/integration_tests/postgres_test.go
Labels: unscheduled, ci

#1515 Bump mariadb from 10.6.16 to 10.6.17
  config/blobs.yml
  packages/database-backup-restorer-mariadb/packaging
Labels: unscheduled, ci

#1524 Add ruby autobumper to BBR SDK
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1525 Bump Ruby to 3.3.0
  Gemfile.lock
Labels: unscheduled, dependencies

#1527 Bump cryogenics/essentials to v0.1.103
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies

#1531 all bumpers should be serial
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1535 Fixed a CI typo
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1536 Add list blob retries
  src/azure-blobstore-backup-restore/container.go
  src/azure-blobstore-backup-restore/container_test.go
  src/azure-blobstore-backup-restore/export_test.go
  src/azure-blobstore-backup-restore/fakes/fake_blob_lister.go
Labels: unscheduled

#1540 Fix/new bumpers
  ci/pipelines/backup-and-restore-sdk-release/pipeline.yml
Labels: unscheduled

#1549 Bump cryogenics/essentials to v0.1.104
  ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.yml
  ci/tasks/create-dev-release/task.yml
  ci/tasks/create-gcp-db-certs/task.yml
  ci/tasks/create-ssl-user/task.yml
  ci/tasks/generate-bosh-deployment-source-file/task.yml
  ci/tasks/sdk-system-blobstore/task.yml
  ci/tasks/sdk-system-db/task.yml
  ci/tasks/sdk-system-db/terraform-task.yml
  ci/tasks/sdk-template-unit-tests/task.yml
  ci/tasks/sdk-unit-blobstore/task.yml
Labels: unscheduled, dependencies
